// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emfhtocfptwrdknlspck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZmh0b2NmcHR3cmRrbmxzcGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTQ4MzIsImV4cCI6MjA2NjA3MDgzMn0.HR6odty1Iv6bNtAysutTaSyPIWjhF1uGWdfS8sHNoMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});